### ISSUE TITLE
Error Reading file

### ISSUE THREAD

**Issue by LucasSovre** [composecraft/docker-compose-lib#2]
### Which browser do you use?

Safari

### What OS do you use?

MacOs

### file content

```yaml
 nextpvr
    image: nextpvr/nextpvr_amd64:stable
    ports:
      - 8866:8866
      - 8020-8030:8020-8030/udp
      - 16891:16891/udp
    devices:
      - /dev/dri:/dev/dri
    restart: always
 controller:
    image: jacobalberty/unifi:v8.0.26
    container_name: unifi_controller
    depends_on:
      - mongo
    init: true
    networks:
      - shared
    restart: always
    volumes:
      - unifidir:/unifi
      - unifiinit:/unifi/init.d
      - unifirun:/var/run/unifi
      #      - unifidata:/unifi/data
      # Mount local folder for backups and autobackups
      - /volume1/config/unifi/backup:/unifi/data/backup
      - /volume1/config/unifi/cert:/unifi/cert
      - /volume1/config/unifi/log:/unifi/log
      - /volume1/config/unifi/data:/unifi/data
    user: unifi
    mem_limit: "1024M"
    #    sysctls:
    #      net.ipv4.ip_unprivileged_port_start: 0
    env_file:
      - ./.env
    environment:
      - DB_URI=mongodb://mongo/unifi
      - STATDB_URI=mongodb://mongo/unifi_stat
      - DB_NAME=<redacted>
      - UNIFI_UID=1028
      - UNIFI_GID=100
      - RUNAS_UID0=false
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8444:8443/tcp" # Controller GUI/API as seen in a web browser
      #      - "8880:8880/tcp" # HTTP portal redirection
      #      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery

```
